In [1]:
import pandas as pd
df = pd.read_csv("salaries_by_college_major.csv")
df.head()

     Undergraduate Major  ...     Group
0             Accounting  ...  Business
1  Aerospace Engineering  ...      STEM
2            Agriculture  ...  Business
3           Anthropology  ...      HASS
4           Architecture  ...  Business

[5 rows x 6 columns]

In [2]:
df.shape

(51, 6)

In [3]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [4]:
df.isna()

    Undergraduate Major  ...  Group
0                 False  ...  False
1                 False  ...  False
2                 False  ...  False
3                 False  ...  False
4                 False  ...  False
5                 False  ...  False
6                 False  ...  False
7                 False  ...  False
8                 False  ...  False
9                 False  ...  False
10                False  ...  False
11                False  ...  False
12                False  ...  False
13                False  ...  False
14                False  ...  False
15                False  ...  False
16                False  ...  False
17                False  ...  False
18                False  ...  False
19                False  ...  False
20                False  ...  False
21                False  ...  False
22                False  ...  False
23                False  ...  False
24                False  ...  False
25                False  ...  False
26                False  ...  False
27                False  ...  False
28                False  ...  False
29                False  ...  False
30                False  ...  False
31                False  ...  False
32                False  ...  False
33                False  ...  False
34                False  ...  False
35                False  ...  False
36                False  ...  False
37                False  ...  False
38                False  ...  False
39                False  ...  False
40                False  ...  False
41                False  ...  False
42                False  ...  False
43                False  ...  False
44                False  ...  False
45                False  ...  False
46                False  ...  False
47                False  ...  False
48                False  ...  False
49                False  ...  False
50                False  ...   True

[51 rows x 6 columns]

In [5]:
df.tail()

      Undergraduate Major  ...  Group
46             Psychology  ...   HASS
47               Religion  ...   HASS
48              Sociology  ...   HASS
49                Spanish  ...   HASS
50  Source: PayScale Inc.  ...    NaN

[5 rows x 6 columns]

In [6]:
clean_df = df.dropna()

In [7]:
clean_df.tail()

   Undergraduate Major  ...  Group
45   Political Science  ...   HASS
46          Psychology  ...   HASS
47            Religion  ...   HASS
48           Sociology  ...   HASS
49             Spanish  ...   HASS

[5 rows x 6 columns]

In [8]:
clean_df["Starting Median Salary"]

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [9]:
clean_df["Starting Median Salary"].max()

74300.0

In [10]:
clean_df["Starting Median Salary"].idxmax()

43

In [11]:
clean_df["Undergraduate Major"].loc[43]

'Physician Assistant'

In [12]:
clean_df["Undergraduate Major"][43]

'Physician Assistant'

In [13]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                             74300
Mid-Career Median Salary                           91700
Mid-Career 10th Percentile Salary                  66400
Mid-Career 90th Percentile Salary                 124000
Group                                               STEM
Name: 43, dtype: object

In [15]:
clean_df["Mid-Career Median Salary"].idxmax()

8

In [17]:
clean_df.loc[8]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                              63200
Mid-Career Median Salary                           107000
Mid-Career 10th Percentile Salary                   71900
Mid-Career 90th Percentile Salary                  194000
Group                                                STEM
Name: 8, dtype: object

In [18]:
clean_df["Starting Median Salary"].idxmin()

49

In [19]:
clean_df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary                 34000
Mid-Career Median Salary               53100
Mid-Career 10th Percentile Salary      31000
Mid-Career 90th Percentile Salary      96400
Group                                   HASS
Name: 49, dtype: object

In [20]:
clean_df["Mid-Career Median Salary"].idxmin()

18

In [21]:
clean_df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary                 34000
Mid-Career Median Salary               53100
Mid-Career 10th Percentile Salary      31000
Mid-Career 90th Percentile Salary      96400
Group                                   HASS
Name: 49, dtype: object

In [22]:
clean_df["Undergraduate Major"].loc[clean_df["Mid-Career Median Salary"].idxmin()]

'Education'

In [23]:
clean_df["Mid-Career 90th Percentile Salary"] - clean_df["Mid-Career 10th Percentile Salary"]

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [24]:
clean_df["Mid-Career 90th Percentile Salary"].subtract(clean_df["Mid-Career 10th Percentile Salary"])

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [27]:
differ_col = clean_df["Mid-Career 90th Percentile Salary"] - clean_df["Mid-Career 10th Percentile Salary"]
clean_df.insert(1, "Spread", differ_col)
clean_df.head()

     Undergraduate Major    Spread  ...  Mid-Career 90th Percentile Salary     Group
0             Accounting  109800.0  ...                           152000.0  Business
1  Aerospace Engineering   96700.0  ...                           161000.0      STEM
2            Agriculture  113700.0  ...                           150000.0  Business
3           Anthropology  104200.0  ...                           138000.0      HASS
4           Architecture   85400.0  ...                           136000.0  Business

[5 rows x 7 columns]

In [31]:
del clean_df["Differ"]
clean_df.head()

     Undergraduate Major  ...     Group
0             Accounting  ...  Business
1  Aerospace Engineering  ...      STEM
2            Agriculture  ...  Business
3           Anthropology  ...      HASS
4           Architecture  ...  Business

[5 rows x 6 columns]

In [32]:
differ_col = clean_df["Mid-Career 90th Percentile Salary"] - clean_df["Mid-Career 10th Percentile Salary"]
clean_df.insert(5, "Differ", differ_col)
clean_df.head()

     Undergraduate Major  Starting Median Salary  ...    Differ     Group
0             Accounting                 46000.0  ...  109800.0  Business
1  Aerospace Engineering                 57700.0  ...   96700.0      STEM
2            Agriculture                 42600.0  ...  113700.0  Business
3           Anthropology                 36800.0  ...  104200.0      HASS
4           Architecture                 41600.0  ...   85400.0  Business

[5 rows x 7 columns]

In [35]:
low_risk = clean_df.sort_values("Differ")
low_risk[["Undergraduate Major", "Differ"]].head()

           Undergraduate Major   Differ
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [37]:
potential = clean_df.sort_values("Mid-Career 90th Percentile Salary", ascending=False)
potential[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [39]:
high_risk = clean_df.sort_values("Differ", ascending=False)
high_risk[["Undergraduate Major", "Differ"]].head()

   Undergraduate Major    Differ
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [40]:
popular = clean_df.sort_values("Mid-Career Median Salary", ascending=False)
popular[["Undergraduate Major", "Mid-Career Median Salary"]].head()

       Undergraduate Major  Mid-Career Median Salary
8     Chemical Engineering                  107000.0
12    Computer Engineering                  105000.0
19  Electrical Engineering                  103000.0
1    Aerospace Engineering                  101000.0
17               Economics                   98600.0

In [41]:
clean_df.groupby("Group").count()

          Undergraduate Major  ...  Differ
Group                          ...
Business                   12  ...      12
HASS                       22  ...      22
STEM                       16  ...      16

[3 rows x 6 columns]

In [42]:
clean_df.groupby("Group").mean()

          Starting Median Salary  ...         Differ
Group                             ...
Business            44633.333333  ...  103958.333333
HASS                37186.363636  ...   95218.181818
STEM                53862.500000  ...  101600.000000

[3 rows x 5 columns]

In [43]:
pd.options.display.float_format = "{:,.2f}".format
clean_df.groupby("Group").mean()

          Starting Median Salary  ...     Differ
Group                             ...
Business               44,633.33  ... 103,958.33
HASS                   37,186.36  ...  95,218.18
STEM                   53,862.50  ... 101,600.00

[3 rows x 5 columns]